---
title: "naive bayes"
author: "Shenghao Wang"
date: "2022-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(naivebayes)
library(dplyr)
library(ggplot2)
library(psych)
library(caret)

```

## R Markdown

```{r}
population <- read.csv('../../data/01-modified-data/cleaned-population-py.csv')
```
```{r}
population <- population[,!(names(population) %in% 'X')]
# normalize death, gdp and birth
population$Deaths_norm = (population$Deaths - mean(population$Deaths))/sd(population$Deaths)
population$GDP_nrom = (population$GDP - mean(population$GDP))/sd(population$GDP)
population$Births_norm = (population$Births - mean(population$Births))/sd(population$Births)
population$Year_norm = (population$Year - mean(population$Year))/sd(population$Year)
population$Label = round(population$Natural_growth_rate)
population<-population[population$Label!=-6,]

population$Label<-as.factor(population$Label)
```




```{r}
trainIndex <- createDataPartition(population$Label,p=0.8,list=FALSE)
train <- population[trainIndex,] #training data
train <- train[, -c(2:6)]
test <- population[-trainIndex,] #testing data 
test <- test[, -c(2:6)]
```


```{r}
#Naive Bayes Classification
model <- naive_bayes(Label ~ -Entity, data = train) 
png(filename="../../501-project-website/images/naive_bayes_r.png")
plot(model) 
dev.off()
```
```{r}
y_pred <- predict(model, newdata = test)
(tab2 <- table(y_pred, test$Label))
1 - sum(diag(tab2)) / sum(tab2)

```
based on the naive bayes classification the misclassification is around 20%

